career/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('portifolio.urls')),
]

portifolio/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView



urlpatterns = [

    path('register/', views.register, name='register'),
    path('accounts/login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/', views.profile, name='profile' ),
    path('profile/<int:user_id>/', views.user_profile, name='user_profile'),

    path("", views.home, name='home'),
    path("categories/", views.categories, name='categories'),
    path("project/<int:pk>/detail", views.project_detail, name='project_detail'),
    path("category/<int:pk>/projects", views.category_projects, name='category_projects'),
    path('projects/language/<str:language>/', views.projects_language, name='projects_language'),
    path('projects/framework/<str:framework>/', views.projects_framework, name='projects_framework'),
    path('update/project/<int:pk>/', views.new_update, name='new_update'),

    # Courses
    path("courses/", views.courses, name='courses'),
    path("course/<int:pk>/detail", views.course_detail, name='course_detail'),
    path("category/<int:pk>/courses", views.category_courses, name='category_courses'),
    path('courses/language/<str:language>/', views.courses_language, name='courses_language'),
    path('courses/framework/<str:framework>/', views.courses_framework, name='courses_framework'),

    path('search/', views.search, name='search'),
    path('metrics/frameworks/<str:language>/', views.framework_progress_language, name='framework_progress_language'),
    path('metrics/frameworks/<int:pk>/', views.framework_progress_category, name='framework_progress_category'),
    path('metrics/<int:pk>/frameworks/', views.framework_progress_category2, name='framework_progress_category2'),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portifolio/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    projects = models.ManyToManyField('Project', related_name='project_categories', blank=True)
    name = models.CharField(max_length=155)
    description = models.TextField()
    image = models.ImageField(upload_to='category/', blank=True, null=True)
    added_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
    	return self.name

class ProgrammingLanguage(models.Model):
    name = models.CharField(max_length=155)

    def __str__(self):
        return self.name

class Framework(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True , related_name='framework_category')
    language = models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE , related_name='framework_language',blank=True, null=True)
    name = models.CharField(max_length=155)

    def __str__(self):
        return self.name

class Project(models.Model):

    BASIC = 1
    REGULAR =2
    HIGH = 4
    PROFESSIONAL = 10
    
    CHOICE = (
        (BASIC, 'Basic'),
        (REGULAR, 'Regular'),
        (HIGH, 'High'),
        (PROFESSIONAL, 'Professional')
    )

    category = models.ManyToManyField(Category, related_name='project')
    updates = models.ForeignKey('Update', related_name='project_updates', on_delete=models.SET_NULL, null=True, blank=True)
    programming_languages = models.ManyToManyField(ProgrammingLanguage, related_name='programming_languages',blank=True)
    frameworks = models.ManyToManyField(Framework, related_name='frameworks',blank=True)
    name = models.CharField(max_length=155)
    description = models.TextField()
    github_link = models.URLField(blank=True, null=True)
    project_link = models.URLField(blank=True, null=True)

    functions = models.TextField(blank=True, null=True)
    possible_upgrades = models.TextField(blank=True, null=True)
    complexity = models.PositiveSmallIntegerField(choices=CHOICE,blank=True, null=True)

    created_at = models.DateField()
    video = models.FileField(upload_to='video_project/', blank=True, null=True)
    image = models.ImageField(upload_to='image_project/', blank=True, null=True)
    added_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.name


class Update(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='update')
    title = models.CharField(max_length=155)
    description = models.TextField()
    image = models.ImageField(upload_to='image_update/', blank=True, null=True)
    video = models.FileField(upload_to='video_update/', blank=True, null=True)
    added_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.title

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    name = models.CharField(max_length=255,  null=True, blank=True)
    company = models.CharField(max_length=255, null=True, blank=True) 
    role = models.CharField(max_length=255, null=True, blank=True) 
    courses = models.ForeignKey("Course", on_delete=models.SET_NULL, null=True, blank=True)
    soft_skills = models.TextField(null=True, blank=True) 
    hard_skills = models.TextField(null=True,blank=True)
    interests = models.TextField(null=True, blank=True) 
    profile_pic = models.ImageField(upload_to ='profile_pic', null=True, blank=True)
    date_created = models.DateTimeField(null=True)

    def __str__(self):
    	return self.name

class Course(models.Model):

    frameworks = models.ManyToManyField(Framework, related_name='course_frameworks',blank=True)
    programming_languages = models.ManyToManyField(ProgrammingLanguage, related_name='course_languages',blank=True)
    category = models.ManyToManyField(Category, related_name='course_category')
    name = models.CharField(max_length=255,  null=True, blank=True)
    company = models.CharField(max_length=255, null=True, blank=True) 
    company_icon = models.FileField(upload_to ='company_icon', null=True, blank=True)
    description = models.TextField(null=True, blank=True) 
    courses = models.IntegerField(blank=True, null=True)
    specialization = models.BooleanField(default=False)
    course_link = models.URLField(null=True, blank=True) 
    licence_link = models.URLField(null=True, blank=True) 
    licence_pic = models.FileField(upload_to ='licence_pic', null=True, blank=True)
    completed_at = models.DateField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
    	return self.name

portifolio/views.py
from multiprocessing import context
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from portifolio.forms import ProjectForm, UpdateForm
from .models import Course, Framework, ProgrammingLanguage, Project, Category, Update
from django.db.models import Count
from django.db.models import Prefetch
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models import Sum
from .forms import CreateUserForm, CustomerForm


def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username or Password is incorrect.')
    context={}
    return render(request, 'registration/login.html', context)    

def logoutUser(request):
    logout(request)
    return redirect('login')       


def register(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUserForm()
        
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')

                messages.success(request, "Welcome " + username + "!")
                
                
                return redirect('login')
        
        
        context = {
            'form':form,
                   }
        
        return render(request, 'registration/register.html', context)

def search(request):
    query = request.GET.get('query', '')
    projects = Project.objects.filter(Q(name__icontains = query) | Q(description__icontains=query) | Q(functions__icontains = query))
    categories = Category.objects.filter(Q(name__icontains = query) | Q(description__icontains=query))
    languages = ProgrammingLanguage.objects.filter(Q(name__icontains = query))
    frameworks = Framework.objects.filter(Q(name__icontains = query))

    context =  {'categories':categories, 'projects':projects , 'query':query,'frameworks':frameworks,'languages':languages}
    
    return render(request, 'search.html', context)

    

@login_required(login_url='login')
def profile(request):
    user = request.user
    customer = user.customer
    form = CustomerForm(instance=customer)
    
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
            
    context = {'form':form,
               'customer':customer,
               }
    return render(request, 'registration/profile.html', context)

def user_profile(request, user_id):
    user = User.objects.get(id=user_id)
    customer = user.customer
    programming_languages = ProgrammingLanguage.objects.all()
    frameworks = Framework.objects.all()
    categories = Category.objects.all()

    language_projects = []
    for language in programming_languages:
        projects = Project.objects.filter(programming_languages__name=language.name)
        courses = Course.objects.filter(programming_languages__name=language.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score=course_sum + project_sum
        frameworks = Framework.objects.filter(language__name=language.name)
        framework_count = frameworks.count()
        language_projects.append({
            'name': language.name,'project_count':project_count, 'project_sum': project_sum, 'course_count': course_count,'course_sum':course_sum, 'score':score, 'framework_count': framework_count  # Wrap the count in a list
            })
        

    framework_projects = []
    for framework in frameworks:
        projects = Project.objects.filter(frameworks__name=framework.name)
        courses = Course.objects.filter(frameworks__name=framework.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score=course_sum + project_sum
        framework_projects.append({'name': framework.name, 'project_count': project_count, 'course_count': course_count,'project_sum': project_sum, 'course_sum':course_sum, 'score':score})
        

    category_projects = []
    for category in categories:
        projects = Project.objects.filter(category__name=category.name)
        courses = Course.objects.filter(category__name=category.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score=course_sum + project_sum
        frameworks = Framework.objects.filter(category__name=category.name)
        framework_count = frameworks.count()
        category_projects.append({'id':category.id,  'name': category.name, 'project_count': project_count, 'course_count': course_count, 'project_sum': project_sum, 'course_sum':course_sum, 'score':score, 'framework_count': framework_count})
        



    context = {
        'customer': customer,
        'user': user,
        'programming_languages': programming_languages,
        'language_projects': language_projects,
        'framework_projects':framework_projects,
        'category_projects':category_projects,
    }
    return render(request, 'registration/user_profile.html', context)

def framework_progress_language(request, language):
    frameworks = Framework.objects.filter(language__name=language)

    framework_projects = []
    for framework in frameworks:
        projects = Project.objects.filter(frameworks__name=framework.name)
        courses = Course.objects.filter(frameworks__name=framework.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score=course_sum + project_sum
        framework_projects.append({'name': framework.name, 'project_count': project_count, 'course_count': course_count,'project_sum': project_sum, 'course_sum':course_sum, 'score':score})
    print(framework_projects)


    context = {
        'framework_projects':framework_projects,
    }
    return render(request, 'framework_progress_language.html', context)


def framework_progress_category2(request, pk):
    category = get_object_or_404(Category, pk=pk)
    frameworks = Framework.objects.filter(category__id=pk)

    framework_projects_category = []
    for framework in frameworks:
        projects = Project.objects.filter(frameworks__name=framework.name)
        courses = Course.objects.filter(frameworks__name=framework.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score = course_sum + project_sum
        framework_projects_category.append({'name': framework.name, 'project_count': project_count, 'course_count': course_count, 'project_sum': project_sum, 'course_sum': course_sum, 'score': score})

    context = {
        'framework_projects_category': framework_projects_category,
        'category': category,
    }

    return render(request, 'framework_progress_category2.html', context)



def framework_progress_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    frameworks = Framework.objects.filter(category__id=pk)

    framework_projects = []
    for framework in frameworks:
        projects = Project.objects.filter(frameworks__name=framework.name)
        courses = Course.objects.filter(frameworks__name=framework.name)
        course_count = courses.count()
        course_sum = courses.aggregate(Sum('courses'))['courses__sum'] or 0
        project_count = projects.count()
        project_sum = projects.aggregate(Sum('complexity'))['complexity__sum'] or 0
        score=course_sum + project_sum
        framework_projects.append({'name': framework.name, 'project_count': project_count, 'course_count': course_count,'project_sum': project_sum, 'course_sum':course_sum, 'score':score})
    print(category)


    context = {
        'framework_projects':framework_projects,
        'category':category,
    },
    return render(request, 'framework_progress_category.html', context)


@login_required(login_url='login')
def new_update(request, pk):
    project = get_object_or_404(Project,pk=pk)

    if request.method == 'POST':
        form = UpdateForm(request.POST, request.FILES)

        if form.is_valid():
            update = form.save(commit=False)
            update.project = project
            update.save()
            project.updates = update
            return redirect('project_detail',pk)

        else:
            print(form.errors)
    else:
        form = UpdateForm()
            
    context = {
        'form':form,'project':project,
               }
    return render(request, 'new_update.html', context)

def home(request):
    projects = Project.objects.annotate(num_updates=Count('updates')).order_by('-added_at')
    languages = ProgrammingLanguage.objects.all()
    frameworks = Framework.objects.all()
    categories = Category.objects.all()

portifolio/templates/category_courses.html
{% extends 'base.html' %}

{% load static %} 

{% block title %} {{category}} {% endblock %}


{% block content %}

<style>
    .columns {
      display: flex;
      flex-wrap: wrap;
      align-items: stretch;
    }
  
    .box {
      display: flex;
      flex-direction: column;
    }
  
    .box-content {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
    }
  
    @media screen and (max-width: 768px) {
    .columns.is-mobile .column.is-one-third {
        width: 100%;
    }
    }

  </style>
  

<section class="hero ">
  <div class="title has-text-centered">
    {{category}} Courses 
  </div>
  <div class="hero-body">

      <div class="columns is-mobile is-multiline" >
        {% for course in courses %}
        <div class="column is-one-third">

          <div class="box is-fullheight" style="height:100%;">
            <div class="box-content" style="height:100%;">
              {% if course.specialization %}
              <div class="">
                <i class="fa-solid fa-crown fa-beat fa-xl is-pulled-right" style="color: #f5ef4d;"></i>
              </div>
              {% endif %}
              
              {% if course.company_icon %}
              <div class="is-pulled-right">
                <img class="image is-pulled-rigth" src="{{course.company_icon.url}}" style="width: 150px; height: 70px;">
              </div>
              {% endif %}

              <div><br>
                {% for category in course.category.all %}
                <a href="{% url 'category_courses' category.id %}" style="color: white;">
                  <tag class="tag is-secondary mb-2" style="background-color: black; color: white;">{{ category.name }}</tag>
              </a>
                {% endfor %} 
              </div>
 
              <div class="">
                {% for language in course.programming_languages.all %}
                  <a href="{% url 'courses_language' language.name %}"><tag class="tag is-primary mb-2">{{language.name}}</tag></a>
                {% endfor %}
                <div>
                  {% for framework in course.frameworks.all %}
                    <a href="{% url 'courses_framework' framework.name %}"><tag class="tag is-info mb-2">{{framework.name}}</tag></a>
                  {% endfor %}

                </div>

                <hr>

              </div>
                <h1 class="title">{{ course.name }} </h1>
                <h3 class="subtitle is-size-7 " style="background-color: white;">Completed at {{ course.completed_at|date:"d/m/Y" }}</h3> 

                <div class="content" style="  display: flex; justify-content: center; align-items: center;">
                    <a href="{{course.licence_link}} ">
                      <img class="image is-48x48" src="{% static 'images/vector-certificate-icon-design.jpg' %} " alt="">
                    </a>
                        
                    <a href="{{course.course_link}} ">
                      <img class="image is-48x48 ml-6" src="{% static 'images/online-course.svg' %} " alt="">
                    </a>
                </div> 
                                          
                <div class="justify-content mt-1">{{ course.description|linebreaks }}</div>

            </div>
          </div>
        </div>
        {% endfor %}
      </div>
  </div>
  </section>

{% endblock %}

portifolio/templates/category_projects.html
{% extends 'base.html' %}

{% load static %} 

{% block title %} projects {% endblock %}


{% block content %}

<style>
    .columns {
      display: flex;
      flex-wrap: wrap;
      align-items: stretch;
    }
  
    .box {
      display: flex;
      flex-direction: column;
    }
  
    .box-content {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
    }
    
  
    @media screen and (max-width: 768px) {
    .columns.is-mobile .column.is-one-half {
        width: 100%;
    }
    }

    .video-container {
        position: relative;
        width: 100%;
        padding-bottom: 56.25%; /* 16:9 aspect ratio (change this value as needed) */
        overflow: hidden;
    }
    
    .video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    @media (max-width: 576px) {
        .video-container {
            padding-bottom: 85%; /* Adjust the aspect ratio for mobile devices */
        }
    }

  </style>
  

<section class="hero ">
  <div class="title has-text-centered">
    {{category.name}} Projects 
  </div>
  <div class="hero-body">

  <div class="columns is-mobile is-multiline">
    {% for project in projects %}
    <div class="column is-one-third">
      <div class="box is-fullheight">
        <div class="box-content">
          <div class="content is-flex is-justify-content-flex-end">
            <h3 class="title is-size-7" style="color: #345998;">
              <i class="fa-solid fa-solid fa-award fa-2xl" style="color: #345998;"></i>
              {{ project.get_complexity_display }}
            </h3>
          </div>
          <div>
              {% for category in project.category.all %}
              <a href="{% url 'category_projects' category.id %}" style="color: white;">
                  <tag class="tag is-secondary mb-2" style="background-color: black; color: white;">{{ category.name }}</tag>
              </a>
              {% endfor %}
          </div>

          <div>
            {% for language in project.programming_languages.all %}
            <a href="{% url 'projects_language' language.name %}">
              <tag class="tag is-primary mb-2">{{ language.name }}</tag>
            </a>
            {% endfor %}
          </div>
          <div>
            {% for framework in project.frameworks.all %}
            <a href="{% url 'projects_framework' framework.name %}">
              <tag class="tag is-info mb-2">{{ framework.name }}</tag>
            </a>
            {% endfor %}
          </div><br>
          <a href="{% url 'project_detail' project.id %}" style="color: black;">
              <h1 class="title">{{ project.name }}</h1>
              <h3 class="subtitle is-size-7" style="background-color: white;">Completed at {{ project.created_at|date:"d/m/Y" }}</h3>
          </a>
          <div class="content is-pulled-right">
            <div class="icon is-pulled-right ">
              <a href="{{ project.github_link }}"><i class="fa-brands fa-square-github fa-2x" style="color: black;"></i></a>
            </div>
            {% if project.project_link %}
            <div class="icon is-pulled-right mr-4 ml-2">
              <a href="{{ project.project_link }}"><i class="fa-solid fa-globe fa-2x" style="color: black;"></i></a>
            </div>
            {% endif %}
          </div>
            <hr>
          {% if project.video %}
          <div class="columns is-centered is-mobile">
            <div class="column is-half">
              <div class="video-container">
                <video class="video" controls preload="auto" poster="{{ project.image.url }}">
                  <source src="{{ project.video.url }}" type="video/mp4">
                  Your browser does not support the video tag.
                </video>
              </div>
            </div>
          </div>
          {% elif project.image %}
          <a href="{% url 'project_detail' project.id %}">
            <div class="hero">
              <figure class="image img is-fullwidth mb-6">
                <img src="{{ project.image.url }}">
              </figure>
            </div>
          </a>
          {% else %}
          <p class="has-text-centered mb-3">No media associated yet.</p>
          {% endif %}
          <hr>

          <div>
            <a href="{% url 'project_detail' project.id %}" style="color: black;">
              <div class="justify-content">{{ project.description|linebreaks }}</div>
            </a>
          </div>

        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</section>

{% endblock %}

<script>
    var player = videojs('my-video');
  </script>

portifolio/templates/home2.html
{% extends 'base.html' %}

{% load static %} 

{% block title %} projects {% endblock %}


{% block content %}

<style>
    .columns {
      display: flex;
      flex-wrap: wrap;
      align-items: stretch;
    }
  

  
    @media screen and (max-width: 768px) {
    .columns.is-mobile .column.is-one-third {
        width: 100%;
    }
    }

    .video-container {
        position: relative;
        width: 100%;
        padding-bottom: 56.25%; /* 16:9 aspect ratio (change this value as needed) */
        overflow: hidden;
    }
    
    .video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    @media (max-width: 576px) {
        .video-container {
            padding-bottom: 95%; /* Adjust the aspect ratio for mobile devices */
        }
    }

  </style>
  

  <section class="hero">
    <div class="title has-text-centered">
        Projects
    </div>
    <div class="hero-body">

          <div>
            <strong> Categories:</strong>
            {% for category in categories %}
            <tag class="tag is-secondary mb-2" style="background-color: black;">
              <a href="{% url 'category_projects' category.id %}" style="color: white;">{{ category.name }}</a>
            </tag>
            {% endfor %}
          </div>
        <div>
            <strong> Languages:</strong>
            {% for language in languages %}
            <a href="{% url 'projects_language' language.name %}">
              <tag class="tag is-primary mb-2">{{ language.name }}</tag>
            </a>
            {% endfor %}
          </div>
          <div>
            <strong> Frameworks:</strong>
            {% for framework in frameworks %}
            <a href="{% url 'projects_framework' framework.name %}">
              <tag class="tag is-info mb-2">{{ framework.name }}</tag>
            </a>
            {% endfor %}
          </div>

          <hr><br>

        <div class="columns is-mobile is-multiline">
          {% for project in projects %}
          <div class="column is-one-third">
            <div class="box is-fullheight">
              <div class="box-content">
                <div class="content is-flex is-justify-content-flex-end">
                  <h3 class="title is-size-7" style="color: #345998;">
                    <i class="fa-solid fa-solid fa-award fa-2xl" style="color: #345998;"></i>
                    {{ project.get_complexity_display }}
                  </h3>
                </div>
                <div>
                    {% for category in project.category.all %}
                    <a href="{% url 'category_projects' category.id %}" style="color: white;">
                        <tag class="tag is-secondary mb-2" style="background-color: black; color: white;">{{ category.name }}</tag>
                    </a>
                    {% endfor %}
                </div>

                <div>
                  {% for language in project.programming_languages.all %}
                  <a href="{% url 'projects_language' language.name %}">
                    <tag class="tag is-primary mb-2">{{ language.name }}</tag>
                  </a>
                  {% endfor %}
                </div>
                <div>
                  {% for framework in project.frameworks.all %}
                  <a href="{% url 'projects_framework' framework.name %}">
                    <tag class="tag is-info mb-2">{{ framework.name }}</tag>
                  </a>
                  {% endfor %}
                </div><br>
                <a href="{% url 'project_detail' project.id %}" style="color: black;">
                    <h1 class="title">{{ project.name }}</h1>
                    <h3 class="subtitle is-size-7" style="background-color: white;">Completed at {{ project.created_at|date:"d/m/Y" }}</h3>
                </a>
                <div class="content is-pulled-right mb-5">
                  <div class="icon is-pulled-right ">
                    <a href="{{ project.github_link }}"><i class="fa-brands fa-square-github fa-2x" style="color: black;"></i></a>
                  </div>
                  {% if project.project_link %}
                  <div class="icon is-pulled-right mr-4 ml-2">
                    <a href="{{ project.project_link }}"><i class="fa-solid fa-globe fa-2x" style="color: black;"></i></a>
                  </div>
                  {% endif %}
                </div>
                  <br><hr>
                {% if project.video %}
                <div class="columns is-centered is-mobile">
                  <div class="column is-half">
                    <div class="video-container">
                      <video class="video" controls preload="auto" poster="{{ project.image.url }}">
                        <source src="{{ project.video.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                      </video>
                    </div>
                  </div>
                </div>
                {% elif project.image %}
                <a href="{% url 'project_detail' project.id %}">
                  <div class="hero">
                    <figure class="image img is-fullwidth mb-6">
                      <img src="{{ project.image.url }}">
                    </figure>
                  </div>
                </a>
                {% else %}
                <p class="has-text-centered mb-3">No media associated yet.</p>
                {% endif %}
                <hr>

                <div>
                  <a href="{% url 'project_detail' project.id %}" style="color: black;">
                    <div class="justify-content">{{ project.description|linebreaks }}</div>
                  </a>
                </div>

              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
  </section>

{% endblock %}

<script>
    var player = videojs('my-video');
  </script>

portifolio/templates/new_update.html
{% extends 'base.html' %}
{% block title %} Details {% endblock %}


{% block content %}



<section class="hero is-fullheight ">
    <div class="hero-body">
        <div class="container">
            New Update
            <form action="{% url 'new_update' project.id %} " method="POST"  enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
              <button type="submit" class="btn-success">ok</button>

            </form>
          </div>
    </div>
  </section>

{% endblock %}